
version: "3"
services:
  cfdb-api:
    build: uwsgi-cfdb-api
    restart: always
    depends_on:
      - redis
      - mongo
      - web
    links:
      - redis:redis
      - mongo:mongo
    volumes:
      - ./cfdb-api:/root/cfdb-api
      - /tmp:/tmp
  cfdb-app:
    build: uwsgi-cfdb-app
    restart: always
    depends_on:
      - redis
      - mongo
      - web
    links:
      - redis:redis
      - mongo:mongo
    volumes:
      - ./cfdb-app:/root/cfdb-app
      - /tmp:/tmp
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./data/certs/.key:/etc/nginx/server.key
      - ./data/certs/.crt:/etc/nginx/server.crt
      - ./api:/root/cfdb-api
      - /tmp:/tmp
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - redis


